import json
import os
cookiesJSON = []

# check if they are dumb enough to run it inside of the scripts directory
cwd = os.getcwd()
# print(cwd)
if cwd.endswith("scripts"):
    print("hey buddy, ur supposed to run this in the project root")
    exit(0)

input("Make sure your reading SELFHOSTING.md before doing this.\nPress enter to continue or ctrl+c to exit")

try:
    with open("cookies.json", 'r') as cookiesFile:
        rawCookiesFileContent = cookiesFile.read()
        cookiesJSON = json.loads(rawCookiesFileContent)

except Exception as leException:
    print(leException)
    print("the error ^^^^^^")
    print("nope not working. are you sure you got the right file?")
    exit(1)

# try to get cookies && check if they exist while ur at it
session_token = "" 
signed_user = ""
try:
    for cookie in cookiesJSON:
        if cookie.get("name") == "signed_user":
            signed_user = cookie.get("value")
        elif cookie.get("name") == "session_token":
            session_token = cookie.get("value")

    if signed_user == "" or session_token == "":
        raise Exception("Tried my best mate but there isnt a signed_user or a session_token in the json u gave me")
except Exception as excep:
    print(excep)
    exit(1)




datatowrite = f"""# automatically generated by import_cookies.py
session_token={session_token}
signed_user={signed_user}
"""
print("Got datatowrite successfully i think")
print(datatowrite)
yassforoverwriting = input("Do you want to save? This will overwrite the current .env (y/N)")
if yassforoverwriting.lower() == "y":
    with open(".env", 'w') as envFile:
        envFile.write(datatowrite)
else:
    print("Alr i wont")
    exit(1)